In [42]:
import random
random.seed(10)
import numpy as np#linear Algebra
import pandas as pd#data processing
data=pd.read_csv('C:/Users/DELL/DESKTOP/kerala.csv')
print(data)

    SUBDIVISION  YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL     AUG  \
0        KERALA  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0   357.5   
1        KERALA  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0   315.8   
2        KERALA  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5   420.2   
3        KERALA  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5   351.8   
4        KERALA  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5   293.6   
..          ...   ...   ...   ...   ...    ...    ...     ...     ...     ...   
113      KERALA  2014   4.6  10.3  17.9   95.7  251.0   454.4   677.8   733.9   
114      KERALA  2015   3.1   5.8  50.1  214.1  201.8   563.6   406.0   252.2   
115      KERALA  2016   2.4   3.8  35.9  143.0  186.4   522.2   412.3   325.5   
116     KERALA   2017   1.9   6.8   8.9   43.6  173.5   498.5   319.6   531.8   
117      KERALA  2018  29.1  52.1  48.6  116.4  183.8   625.4  1048.5  1398.9   

       SEP    OCT    NOV   

In [43]:
data.head()

SUBDIVISION  YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL    AUG  \
0      KERALA  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0  357.5   
1      KERALA  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0  315.8   
2      KERALA  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5  420.2   
3      KERALA  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5  351.8   
4      KERALA  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5  293.6   

     SEP    OCT    NOV    DEC   ANNUAL RAINFALL FLOODS  
0  197.7  266.9  350.8   48.4            3248.6    YES  
1  491.6  358.4  158.3  121.5            3326.6    YES  
2  341.8  354.1  157.0   59.0            3271.2    YES  
3  222.7  328.1   33.9    3.3            3129.7    YES  
4  217.2  383.5   74.4    0.2            2741.6     NO

In [44]:
data.tail()

SUBDIVISION  YEAR   JAN   FEB   MAR    APR    MAY    JUN     JUL     AUG  \
113      KERALA  2014   4.6  10.3  17.9   95.7  251.0  454.4   677.8   733.9   
114      KERALA  2015   3.1   5.8  50.1  214.1  201.8  563.6   406.0   252.2   
115      KERALA  2016   2.4   3.8  35.9  143.0  186.4  522.2   412.3   325.5   
116     KERALA   2017   1.9   6.8   8.9   43.6  173.5  498.5   319.6   531.8   
117      KERALA  2018  29.1  52.1  48.6  116.4  183.8  625.4  1048.5  1398.9   

       SEP    OCT    NOV   DEC   ANNUAL RAINFALL FLOODS  
113  298.8  355.5   99.5  47.2            3046.4    YES  
114  292.9  308.1  223.6  79.4            2600.6     NO  
115  173.2  225.9  125.4  23.6            2176.6     NO  
116  209.5  192.4   92.5  38.1            2117.1     NO  
117  423.6  356.1  125.4  65.1            4473.0    YES

FINDING THE NUMBER OF MISSING VALUES

In [45]:
data.isnull().sum()

SUBDIVISION         0
YEAR                0
JAN                 0
FEB                 0
MAR                 0
APR                 0
MAY                 0
JUN                 0
JUL                 0
AUG                 0
SEP                 0
OCT                 0
NOV                 0
DEC                 0
 ANNUAL RAINFALL    0
FLOODS              0
dtype: int64

In [46]:
data.describe()

YEAR         JAN         FEB         MAR         APR  \
count   118.000000  118.000000  118.000000  118.000000  118.000000   
mean   1959.500000   12.218644   15.633898   36.670339  110.330508   
std      34.207699   15.473766   16.406290   30.063862   44.633452   
min    1901.000000    0.000000    0.000000    0.100000   13.100000   
25%    1930.250000    2.175000    4.700000   18.100000   74.350000   
50%    1959.500000    5.800000    8.350000   28.400000  110.400000   
75%    1988.750000   18.175000   21.400000   49.825000  136.450000   
max    2018.000000   83.500000   79.000000  217.200000  238.000000   

              MAY          JUN          JUL          AUG         SEP  \
count  118.000000   118.000000   118.000000   118.000000  118.000000   
mean   228.644915   651.617797   698.220339   430.369492  246.207627   
std    147.548778   186.181363   228.988966   181.980463  121.901131   
min     53.400000   196.800000   167.500000   178.600000   41.300000   
25%    125.050000   535.550000   533.200000   316.725000  155.425000   
50%    184.600000   625.600000   691.650000   386.250000  223.550000   
75%    264.875000   786.975000   832.425000   500.100000  334.500000   
max    738.800000  1098.200000  1526.500000  1398.900000  526.700000   

              OCT         NOV         DEC   ANNUAL RAINFALL  
count  118.000000  118.000000  118.000000        118.000000  
mean   293.207627  162.311017   40.009322       2925.405085  
std     93.705253   83.200485   36.676330        452.169407  
min     68.500000   31.500000    0.100000       2068.800000  
25%    222.125000   93.025000   10.350000       2613.525000  
50%    284.300000  152.450000   31.100000       2934.300000  
75%    355.150000  218.325000   54.025000       3170.400000  
max    567.900000  365.600000  202.300000       4473.000000

In [47]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   SUBDIVISION       118 non-null    object 
 1   YEAR              118 non-null    int64  
 2   JAN               118 non-null    float64
 3   FEB               118 non-null    float64
 4   MAR               118 non-null    float64
 5   APR               118 non-null    float64
 6   MAY               118 non-null    float64
 7   JUN               118 non-null    float64
 8   JUL               118 non-null    float64
 9   AUG               118 non-null    float64
 10  SEP               118 non-null    float64
 11  OCT               118 non-null    float64
 12  NOV               118 non-null    float64
 13  DEC               118 non-null    float64
 14   ANNUAL RAINFALL  118 non-null    float64
 15  FLOODS            118 non-null    object 
dtypes: float64(13), int64(1), object(2)
memory u

In [48]:
#replacing the yes/no in flood coloumn by 1/0
data['FLOODS'].replace(['YES','NO'],[1,0],inplace=True)

In [49]:
data.head()

SUBDIVISION  YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL    AUG  \
0      KERALA  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0  357.5   
1      KERALA  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0  315.8   
2      KERALA  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5  420.2   
3      KERALA  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5  351.8   
4      KERALA  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5  293.6   

     SEP    OCT    NOV    DEC   ANNUAL RAINFALL  FLOODS  
0  197.7  266.9  350.8   48.4            3248.6       1  
1  491.6  358.4  158.3  121.5            3326.6       1  
2  341.8  354.1  157.0   59.0            3271.2       1  
3  222.7  328.1   33.9    3.3            3129.7       1  
4  217.2  383.5   74.4    0.2            2741.6       0

In [50]:
#seperating x and y
x=data.iloc[:,1:14]
x.head()

YEAR   JAN   FEB   MAR    APR    MAY     JUN     JUL    AUG    SEP    OCT  \
0  1901  28.7  44.7  51.6  160.0  174.7   824.6   743.0  357.5  197.7  266.9   
1  1902   6.7   2.6  57.3   83.9  134.5   390.9  1205.0  315.8  491.6  358.4   
2  1903   3.2  18.6   3.1   83.6  249.7   558.6  1022.5  420.2  341.8  354.1   
3  1904  23.7   3.0  32.2   71.5  235.7  1098.2   725.5  351.8  222.7  328.1   
4  1905   1.2  22.3   9.4  105.9  263.3   850.2   520.5  293.6  217.2  383.5   

     NOV    DEC  
0  350.8   48.4  
1  158.3  121.5  
2  157.0   59.0  
3   33.9    3.3  
4   74.4    0.2

In [51]:
y=data.iloc[:,-1]
y

0      1
1      1
2      1
3      1
4      0
      ..
113    1
114    0
115    0
116    0
117    1
Name: FLOODS, Length: 118, dtype: int64

PLOTTING THE DATA

In [52]:
import matplotlib.pyplot as plt
#set the backend of matplotlib to inline backend
%matplotlib inline
c=data[['JUN','JUL','AUG','SEP']]
c.hist()
plt.show()
#how the rainfall index vary each season

In [53]:
ax=data[['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC']].mean()
print(ax)

JAN     12.218644
FEB     15.633898
MAR     36.670339
APR    110.330508
MAY    228.644915
JUN    651.617797
JUL    698.220339
AUG    430.369492
SEP    246.207627
OCT    293.207627
NOV    162.311017
DEC     40.009322
dtype: float64


USING SKLEARN TO DEVELOP THE ML MODEL

In [54]:
from sklearn import preprocessing
minmax=preprocessing.MinMaxScaler(feature_range=(0,1))
minmax.fit(x).transform(x)

array([[0.        , 0.34371257, 0.56582278, ..., 0.39727673, 0.95570189,
        0.2388724 ],
       [0.00854701, 0.08023952, 0.03291139, ..., 0.5804966 , 0.37952709,
        0.60039565],
       [0.01709402, 0.03832335, 0.23544304, ..., 0.57188626, 0.37563604,
        0.29129575],
       ...,
       [0.98290598, 0.02874251, 0.04810127, ..., 0.31517821, 0.28105358,
        0.11622156],
       [0.99145299, 0.02275449, 0.08607595, ..., 0.24809772, 0.18258007,
        0.18793274],
       [1.        , 0.34850299, 0.65949367, ..., 0.57589107, 0.28105358,
        0.3214639 ]])

In [55]:
from sklearn import model_selection,neighbors
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

YEAR   JAN   FEB   MAR    APR    MAY     JUN    JUL    AUG    SEP    OCT  \
41   1942   2.4   4.7  23.2  180.3  191.9   813.6  828.8  329.3   99.8  374.4   
3    1904  23.7   3.0  32.2   71.5  235.7  1098.2  725.5  351.8  222.7  328.1   
116  2017   1.9   6.8   8.9   43.6  173.5   498.5  319.6  531.8  209.5  192.4   
110  2011  20.5  45.7  24.1  165.2  124.2   788.5  536.8  492.7  391.2  227.2   
49   1950   0.1  53.7  31.1   68.5  242.0   638.3  905.7  387.3  411.6  250.4   
..    ...   ...   ...   ...    ...    ...     ...    ...    ...    ...    ...   
94   1995  10.3   6.5  37.3  134.9  355.6   493.4  702.5  457.3  280.0  198.3   
62   1963  30.2  24.8  69.8   96.3  157.1   393.3  720.2  511.0  223.9  282.6   
28   1929  12.8  29.8  58.9  210.7  148.0   946.6  844.0  293.9  268.9  350.4   
33   1934  74.5   1.7  47.7   92.4  106.7   852.9  415.0  337.2   48.4  335.9   
56   1957   1.2  16.0  25.7   70.2  381.2   872.0  835.3  358.8   41.3  280.1   

       NOV    DEC  
41    84.7  117.9  
3     33.9    3.3  
116   92.5   38.1  
110  169.7   49.5  
49   149.2    8.8  
..     ...    ...  
94   182.6    0.1  
62    93.4   48.4  
28   158.2   39.4  
33    93.4    4.9  
56   192.5   28.9  

[94 rows x 13 columns]

In [26]:
x_test

YEAR   JAN   FEB   MAR    APR    MAY    JUN     JUL    AUG    SEP    OCT  \
18   1919  43.0   6.1  33.9   65.9  247.0  636.8   648.0  484.2  255.9  249.2   
41   1942   2.4   4.7  23.2  180.3  191.9  813.6   828.8  329.3   99.8  374.4   
49   1950   0.1  53.7  31.1   68.5  242.0  638.3   905.7  387.3  411.6  250.4   
13   1914   0.7   6.8  18.1   32.7  164.2  565.3   857.7  402.2  241.0  374.4   
19   1920  35.2   5.5  24.1  172.0   87.7  964.3   940.8  235.0  178.0  350.1   
28   1929  12.8  29.8  58.9  210.7  148.0  946.6   844.0  293.9  268.9  350.4   
108  2009   3.3   1.5  62.6   69.0  191.6  438.2   924.9  269.3  326.5  205.2   
101  2002   4.7   8.7  35.7  117.3  330.8  503.1   318.7  438.2   99.0  511.7   
16   1917   2.9  47.6  79.4   38.1  122.9  703.7   342.7  335.1  470.3  264.1   
37   1938   0.3  79.0  53.3  164.5  179.6  681.6   648.6  287.9  223.2  223.7   
71   1972   2.6   7.5   2.5   87.5  436.0  401.8   714.4  294.9  185.7  351.5   
38   1939  13.6   3.6  24.9  172.8  105.1  625.8   749.6  459.9  134.1  339.8   
63   1964   1.1   7.8  67.2   83.3   94.8  379.4   754.2  548.0  398.2  325.7   
109  2010  18.6   1.0  31.4  138.9  190.6  667.5   629.0  356.0  275.6  441.4   
99   2000  11.7  57.8  21.5   96.3  124.5  633.8   343.2  566.5  195.8  214.2   
0    1901  28.7  44.7  51.6  160.0  174.7  824.6   743.0  357.5  197.7  266.9   
50   1951   6.6   6.5  41.6  175.9  148.5  774.1   544.6  190.6  313.8  250.6   
32   1933   1.0   9.3  36.9  139.5  738.8  859.3   773.4  479.5  469.7  397.0   
10   1911   3.0   4.3  18.2   51.0  180.6  990.0   705.3  178.6   60.2  302.3   
89   1990  14.9   4.8  18.0   41.8  488.5  528.6   635.4  370.8  103.3  323.2   
74   1975   5.2  21.4  63.4  123.8  162.2  864.4   531.3  675.9  457.7  368.9   
115  2016   2.4   3.8  35.9  143.0  186.4  522.2   412.3  325.5  173.2  225.9   
58   1959   3.0  21.4   6.3  150.7  347.2  872.8  1155.7  397.3  405.5  200.4   
33   1934  74.5   1.7  47.7   92.4  106.7  852.9   415.0  337.2   48.4  335.9   

       NOV    DEC  
18   280.1   53.0  
41    84.7  117.9  
49   149.2    8.8  
13   100.9  135.2  
19   302.3    8.2  
28   158.2   39.4  
108  274.4   44.2  
101  137.5    2.1  
16   256.4   41.6  
37    69.5   22.9  
71   140.5  114.3  
38   298.1   10.2  
63   191.7   17.8  
109  335.1   46.8  
99    78.1   69.1  
0    350.8   48.4  
50   229.6   23.2  
32   126.1   42.3  
10   145.7   87.6  
89   158.8    5.2  
74   204.3   19.9  
115  125.4   23.6  
58   151.9   34.0  
33    93.4    4.9

In [58]:
y_train=y_train.astype('int')
y_train

41     1
3      1
116    0
110    1
49     1
      ..
94     0
62     0
28     1
33     0
56     1
Name: FLOODS, Length: 94, dtype: int32

In [59]:
y_test=y_test.astype('int')
y_test

111    0
4      0
23     1
12     0
11     1
106    1
82     0
26     1
7      0
78     0
10     0
20     0
98     0
59     1
42     1
38     1
46     1
29     1
89     0
36     0
22     1
0      1
65     0
100    0
Name: FLOODS, dtype: int32

LOGISTIC REGRESSION TO PREDICT

In [73]:
x_train_std=minmax.fit_transform(x_train)
print(x_train_std)

[[0.34482759 0.03221477 0.05949367 ... 0.64440699 0.15923376 0.58259149]
 [0.01724138 0.31812081 0.03797468 ... 0.54687171 0.00718348 0.01582591]
 [0.99137931 0.02550336 0.08607595 ... 0.26100695 0.18258007 0.18793274]
 ...
 [0.23275862 0.17181208 0.37721519 ... 0.59384875 0.37922778 0.19436202]
 [0.27586207 1.         0.02151899 ... 0.56330314 0.18527387 0.02373887]
 [0.47413793 0.01610738 0.20253165 ... 0.44575521 0.48189165 0.14243323]]


In [61]:
from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.linear_model import LogisticRegression

In [62]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr_acc=cross_val_score(lr,x_train_std,y_train,cv=3,scoring='accuracy',n_jobs=-1)
lr_proba=cross_val_predict(lr,x_train_std,y_train,cv=3,method='predict_proba')

D:\VS\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [63]:
lr_acc

array([0.8125    , 0.83870968, 0.80645161])

In [64]:
lr_proba

array([[0.5897063 , 0.4102937 ],
       [0.2983309 , 0.7016691 ],
       [0.7696297 , 0.2303703 ],
       [0.44531597, 0.55468403],
       [0.26823571, 0.73176429],
       [0.40929148, 0.59070852],
       [0.51189829, 0.48810171],
       [0.3701461 , 0.6298539 ],
       [0.34282428, 0.65717572],
       [0.74538501, 0.25461499],
       [0.26658433, 0.73341567],
       [0.5794107 , 0.4205893 ],
       [0.62864766, 0.37135234],
       [0.70132746, 0.29867254],
       [0.51877166, 0.48122834],
       [0.4212901 , 0.5787099 ],
       [0.60523352, 0.39476648],
       [0.28544897, 0.71455103],
       [0.2222035 , 0.7777965 ],
       [0.63110828, 0.36889172],
       [0.64612429, 0.35387571],
       [0.23803918, 0.76196082],
       [0.79365041, 0.20634959],
       [0.4608258 , 0.5391742 ],
       [0.16799877, 0.83200123],
       [0.29082509, 0.70917491],
       [0.21044871, 0.78955129],
       [0.50505329, 0.49494671],
       [0.29093853, 0.70906147],
       [0.19675157, 0.80324843],
       [0.

In [71]:
y_pred=lr.predict(x_test)
y_pred

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1])

In [72]:
print(y_test.values)

[0 0 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0]


In [67]:
print("List of Predicted Values:")
print(y_pred)

List of Predicted Values:
[0 0 1 0 1 1 0 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1]


In [68]:
from sklearn.metrics import accuracy_score,recall_score,roc_auc_score,confusion_matrix
print("\naccuracy score:%f"%(accuracy_score(y_test,y_pred)*100))
print("\nrecall score:%f"%(recall_score(y_test,y_pred)*100))
print("\nroc score:%f"%(roc_auc_score(y_test,y_pred)*100))
print(confusion_matrix(y_test,y_pred))


accuracy score:95.833333

recall score:100.000000

roc score:96.153846
[[12  1]
 [ 0 11]]
